### ISSUE TITLE
Inspector in tab

### ISSUE THREAD

**Issue by afmarchetti** [sean-codes/atom-browser#18]
is possible have the inspector in a tab and not in a popup, with popup if you inspect you have click multiple times to activate the window, thanks! ;-)

**Comment by sean-codes** [comment]
@afmarchetti Hi!! I believe this may not be possible due to the way electron does webviews (i think if it was supported we would see the dock options available) . Maybe a workaround would be using two webviews and connecting them by opening the inspector url in one. We would likely need to open that in another dock or tab. I think it might be possible with a bit of work. For this simple plugin I would hope to keep it simple and might have to skip this feature!
